# Generated by Django 6.0.4 on 2026-04-21 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("course", models.CharField(max_length=50)),
                ("study_hours", models.FloatField()),
                ("sleep_hours", models.FloatField()),
                ("attendance_percentage", models.FloatField()),
                ("prediction", models.FloatField()),
                ("grade", models.CharField(max_length=5)),
                ("pass_or_fail", models.CharField(max_length=50)),
                ("zai_output", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
