# Generated by Django 6.0.4 on 2026-04-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="history",
            name="screen_time",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
