# Generated by Django 6.0.4 on 2026-04-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_history_screen_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="history",
            name="risk",
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="history",
            name="risk_class",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="history",
            name="zai_output",
            field=models.JSONField(),
        ),
    ]
